# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f68a33b70b071b13d78d2db80a4191a702bcb00ea7023fcec2327253807b7fb79c5471dac68adcffd9e77b46920c30eaf3155df430bef2560b9fb958d6d8d41

test:
  secret_key_base: 5944775a192f174d541f46adb17880546ee348b82ffbb4120fbb75d452a9fe5c72413334d1d1bb0edf02f169c982c93f1dd1c099d992df3514ea38aeca04834c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
